spring:
  data:
    mongodb:
      host: localhost
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zhcore?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    defaultAutoCommit: false

mybatis:
  type-aliases-package: com.pwc.zhcore.resource.domain.mybatis
  mapper-locations: classpath:/mybatis/**/*.xml

server:
  context-path: /resource
  port: 0
